Document Fetching
Salisbury-University/hslinux-web-backend pull request #10
Opened 2022-04-27 19:11 UTC by dylmcd13

Has routes and implementation for fetching all documents, all documents with pagination, and single documents. The markdown frontmatter is parsed with the mark.js file then stored in the database. The fetching document parts check the database.

2022-04-27 19:52 UTC, SpencerLefever reviewed
Don't pay attention to mine if Chris suggests something different

2022-04-27 19:52 UTC, SpencerLefever commented on app/http/controllers/DocumentController.ts
> +    console.log("IN DOC CONTROLLER: multiDoc()");
console.log should not be in the final production branch

2022-04-27 19:52 UTC, SpencerLefever commented on app/http/middleware/ExampleMiddleware.ts
>    req: Request,
I think you can just remove the ExampleMiddleware.ts file

2022-04-27 19:52 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +      res.sendStatus(404);
throw a new error with the exception handler instead of sending a res.sendStatus

2022-04-27 19:52 UTC, SpencerLefever commented on mark.js
> +const { marked } = require('marked');
Why is this a javascript file and not a typescript file?

2022-04-27 20:04 UTC, SpencerLefever commented
Also UNIT TESTING!!!

2022-09-02 16:28 UTC, SpencerLefever requested changes

2022-09-02 16:28 UTC, SpencerLefever commented on app.ts
> +import authRouter from "./app/routes/auth";
Import authRouter in app/http/routes/index.ts so the app.ts file is clean and just has the indexRouter imported

2022-09-02 16:28 UTC, SpencerLefever commented on app.ts
> +app.use(authRouter);
This should be moved to app/http/routes/index.ts (Look in master branch file for reference)

2022-09-02 16:28 UTC, SpencerLefever commented on app.ts
> +//app.use(ExampleMiddleware);
Middleware should be imported and used app/routes/auth.ts (Refer to master branch file for example)

2022-09-02 16:28 UTC, SpencerLefever commented on app.ts
> +
This might want to also be in app/http/routes/index.ts to keep this file clean?

2022-09-02 16:28 UTC, SpencerLefever commented on app/exceptions/DocumentException.ts
> +}
Should follow format/style of exception handlers on master branch

2022-09-02 16:28 UTC, SpencerLefever commented on app/exceptions/PageException.ts
> +}
Also should follow format/style of exception handlers on master branch

2022-09-02 16:28 UTC, SpencerLefever commented on app/http/controllers/DocumentController.ts
> +      return next;
Implementation should be written in the service. The controller should simply call the service funtion and catch any errors thrown by the service function. Look at the master branch authController for example

2022-09-02 16:28 UTC, SpencerLefever commented on app/routes/documents.ts
> +router.get("/api/v1/doc/:id", DocumentController.singleDoc);
Move the "/api/v1/doc(s)" roots into app/routes/index.ts. Look at master branch file for example

2022-09-02 16:28 UTC, SpencerLefever commented on app/routes/index.ts
> +router.use(documentRouter);
This is where the root of the routes should be

2022-09-02 16:28 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +};
Service functions should either throw an error with the exception handler or return data.

2022-09-02 16:28 UTC, SpencerLefever commented on prisma/migrations/20220401141829_login_test_migration/migration.sql
> +-- CreateTable
Remove prisma stuff

2022-09-02 22:14 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +   * If the document is found, sends id, content, and metadata to Body
use the @throws tool for comments regarding errors throwing "@throws <Exception>"

2022-09-09 17:14 UTC, SpencerLefever requested changes

2022-09-09 17:14 UTC, SpencerLefever commented on app/exceptions/DocumentException.ts
> +  constructor(message: string = "Document Not Found") {
Use general http status codes and messages

2022-09-09 17:14 UTC, SpencerLefever commented on app/routes/index.ts
> +router.get("/api/v1/doc/:id", DocumentController.singleDoc);
have the root "api/v1/doc(s)" of the routes in here and individual routes in documents.ts file

2022-09-09 17:14 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +    //also need to check if the page contains letters, since we dont want letters in the page parameter
try implementing input validation with zod. I have some written up on the preference branch in the app/schema folder

2022-09-09 17:14 UTC, SpencerLefever commented on mark.ts
> +const { marked } = require("marked");
FInd a home for these function. Possibly in the service file

2022-09-09 17:40 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +            dateUpdated: document.updatedDate,
Since this is in the service file, this function is being called by the controller. So I believe you want to return the data instead of res.send and use the controller to res.send. This technique should be implemented in all service functions

2022-09-12 16:28 UTC, SpencerLefever requested changes

2022-09-12 16:28 UTC, SpencerLefever commented on app/exceptions/DocumentException.ts
> +    super(message, 404);
File name and message should be consistent with exceptions already on master branch

2022-09-12 16:28 UTC, SpencerLefever commented on app/exceptions/PageException.ts
> +    super(message, 400);
File name and message should be consistent with exceptions already on master branch

2022-09-12 16:28 UTC, SpencerLefever commented on app/http/controllers/DocumentController.ts
> +      next(error);
i think we want to return next(err). This is nit picky but I used the err abbreviation if you have a chance the change  it to keep consistent.

2022-09-15 11:32 UTC, SpencerLefever requested changes
Everything looked really good. I think we should be ready for Chris to review after these last few minor changes

2022-09-15 11:32 UTC, SpencerLefever commented on app/routes/index.ts
> +router.use("/api/v1", DocumentRouter);
put the /docs in this router because as of right now, all requests on /api/v1 will go to the doc router.
i.e. in this file have "/api/v1/docs" and in routes/documents.ts have "/", "/:page", and "/:id" respectively.

2022-09-15 11:32 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +   * @throws 'PageException' when the page is less than 1
update @throws to reflect changes

2022-09-15 11:32 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +   * @throws 'DocumentNotFoundException' when the document id given does not exist
update @throws

2022-09-15 11:32 UTC, SpencerLefever commented on app/services/DocumentService.ts
> +          return;
Not sure what this is for. Might want to throw the error instead of returning nothing

2022-09-15 11:32 UTC, SpencerLefever commented on app/services/mark.ts
> +const { marked } = require("marked");
possibly change the file name to something like MarkService or MarkdownService to reflect its functionality

2022-09-16 14:26 UTC, SpencerLefever commented on app/routes/index.ts
> +router.use("/api/v1", DocumentRouter);
*** In app/routes/index.ts
#+BEGIN_SRC typescript :exports code
router.use("/api/v1/docs", DocumentRouter);
#+END_SRC

***In app/routes/documents.ts
#+BEGIN_SRC typescript :exports code

router.get("/", DocumentController.multiDoc);

router.get("/:page", DocumentController.multiDocPages);

router.get("/:id", DocumentController.singleDoc);

#+END_SRC

2022-09-16 16:36 UTC, dylmcd13 commented on app/routes/index.ts
> +router.use("/api/v1", DocumentRouter);
So in index.ts, there needs to be 2 routes then since I need the route 'api/v1/docs' for multiple documents and the route 'api/v1/doc' for a single document with ID, but if i send them both to the same router, then the root route '/' in documents.ts would be used for both 'api/v1/docs' and 'api/v1/doc'. I was thinking about splitting the '/api/v1/docs' routes into one file for multiple documents and and '/api/v1/doc' to another file for single documents. I feel like this might be too confusing but I haven't found another way yet.

2022-09-16 17:32 UTC, dylmcd13 commented on app/routes/index.ts
> +router.use("/api/v1", DocumentRouter);
I separated the DocumentRouter into singleDocument and multiDocument

2022-09-21 16:39 UTC, wrathofrathma approved these changes
Approved, contingent on 
- Merge requests for non-doc related things prioritizing the master branch
- Fix the changes

2022-09-21 16:39 UTC, wrathofrathma commented on app/services/mark.ts
> +const { marked } = require("marked");
Duplicate file

2022-09-21 16:39 UTC, wrathofrathma commented on app/http/controllers/DocumentController.ts
> +   * Sends Request and Response to multiDoc() Service
Add routes to the docstrings. It's really informative if there are things like :id parameters.

This is grabbing al lthe docs, specify that

2022-09-21 16:39 UTC, wrathofrathma commented on app/http/controllers/DocumentController.ts
> +        const documentsPaged = await DocumentService.multiDocPaged(req.params.page);
Add input validation using the zod library.

2022-09-21 16:39 UTC, wrathofrathma commented on app/http/controllers/DocumentController.ts
> +      const singleDocument = await DocumentService.singleDoc(req.params.id);
add input validation using zod

2022-09-21 16:39 UTC, wrathofrathma commented on app/services/DocumentService.ts
> +import BaseException from "../exceptions/BaseException";
Unused import

2022-09-21 16:39 UTC, wrathofrathma commented on app/services/DocumentService.ts
> +   * Takes the page number from the request and puts the 10 documents into JSON Body
Clarify it's grabbing the IDs

2022-09-21 16:39 UTC, wrathofrathma commented on app/services/DocumentService.ts
> +    var index = 0,
don't use var, const is sufficient

2022-09-21 16:39 UTC, wrathofrathma commented on app/services/DocumentService.ts
> +    if (file.endsWith(".md")) {
Put in a task to make this not care if things are in order.

2022-09-21 17:07 UTC, dylmcd13 commented on app/services/DocumentService.ts
> +    var index = 0,
Using let instead of const since I am incrementing these values

2022-09-23 16:50 UTC, SpencerLefever approved these changes
lgtm

2022-09-23 17:14 UTC, merged