Login/Logout Routes
Salisbury-University/hslinux-web-backend pull request #8
Opened 2022-04-04 19:38 UTC by SpencerLefever

These two commits were just for the login and logout routes. I am going to start on the Authentication Middleware. I believe the exampleMiddleware is currently commented out in the app.ts folder on my branch. I just wanted to let you know in case that is an issue

2022-04-05 05:22 UTC, wrathofrathma requested changes
Fix the requested changes and write unit tests for every new feature you implement.

2022-04-05 05:22 UTC, wrathofrathma commented on app/routes/auth.ts
> +//router.get("/", IndexController.index);
we can just get rid of these lines entirely.

2022-04-05 15:23 UTC, SpencerLefever commented on prisma/migrations/20220401141829_login_test_migration/migration.sql
> +CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
Prisma created these as there example when I tried to create a user table. These extra tables are useless I will take them out on the next commit

2022-04-12 14:19 UTC, wrathofrathma requested changes
- Check your unit tests. None of them are passing. 
- Not all of the issues were resolved from the last review
- Add the LDAP url to the config and load it from the .env that you've set up. This will allow for default values in the event we don't have a .env.

2022-04-12 14:19 UTC, wrathofrathma commented on app/routes/auth.ts
> +AuthRouter.post('/api/v1/auth/login', validate(login), AuthController.login);
By expanding to the full route here, the route ends up being /auth/api/v1/auth/login because the auth router is included in the app/routes/index.ts under "/auth". 

Probably worthwhile just keeping the relative routes here and having the full prefix at the router inclusion level. I.e. this here
```typescript
AuthRouter.post('/login', validate(login), AuthController.login);
```
Then in index.ts you'd specify the /api/v1/auth.

2022-04-12 14:19 UTC, wrathofrathma commented on app/routes/auth.ts
> +import login from "../schema/login";
Import the schema as something more descriptive, such as loginSchema or AuthLoginSchema. Mostly to set up the habit of being verbose.

2022-04-12 14:19 UTC, wrathofrathma commented on app/routes/index.ts
> +import schema from "../schema/login";
This is not being used.

2022-04-12 14:19 UTC, wrathofrathma commented on app/schema/login.ts
> +});
Content is good. However, you should rename this file to something more specific.

Once we get a bunch of routes, it'll be easier to see them at a glance if they're named in some format like RouterRouteMethod, for this one that'd be something like AuthLoginPost.ts

2022-04-12 14:19 UTC, wrathofrathma commented on app/services/AuthService.ts
> +require('dotenv').config();
We don't need dotenv.config() here. This is one of the first things run in the application.

2022-04-12 14:19 UTC, wrathofrathma commented on app/services/AuthService.ts
> +        url: process.env.AUTH_URL,
Should change this to something from config. You already imported it, so i think you were planning on it.

2022-04-25 20:07 UTC, wrathofrathma requested changes

2022-04-25 20:07 UTC, wrathofrathma commented on app/http/middleware/AuthMiddleware.ts
> +        AuthService.login(decodeBody.uid, decodeBody.password);
Defining the express request ot have a user object
https://github.com/Salisbury-University/cyber-security-backend/blob/master/%40types/express/index.d.ts

Add the type path to the tsconfig.json

```diff
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "rootDir": "./",
    "esModuleInterop": true,
    "typeRoots": [
+     "@types",
+      "./node_modules/@types"
    ]
  }
}
```

After defining the express request type, attach the user object to the request 
```typescript
req.user = AuthService.login(decodeBody.uid, decodeBody.password);
```

2022-04-25 20:07 UTC, wrathofrathma commented on app/services/AuthService.ts
> +    },
Combine these into one function.

// TODO consider throwing instead of returning t/f

2022-05-10 16:37 UTC, wrathofrathma commented on app/http/controllers/AuthController.ts
> +  },
👀  what is this for

2022-05-10 16:47 UTC, wrathofrathma commented on app/routes/auth.ts
> +AuthRouter.get("/test", AuthController.test)
👀

2022-05-10 16:55 UTC, wrathofrathma commented on app/services/AuthService.ts
> +    AuthService.login(decodeBody.uid, decodeBody.password);
JWT data is publicly visible. This is getting boomed. In the future there will be a validation route on the LDAP API. but for now just remove this.

2022-05-10 16:56 UTC, wrathofrathma commented on app/services/AuthService.ts
>    },
no

2022-05-10 17:57 UTC, merged